extends:
  - "@commitlint/config-conventional"

rules:
  # Allow these types
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
      - security

  # Max header length
  header-max-length:
    - 2
    - always
    - 100

  # Subject must not be empty
  subject-empty:
    - 2
    - never

  # Type must not be empty
  type-empty:
    - 2
    - never
