# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint

# Default state for all rules
default: true

# MD003/heading-style - Heading style
MD003:
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD013/line-length - Line length (disabled for flexibility)
MD013: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!"

# MD028/no-blanks-blockquote - Blank line inside blockquote
# Disabled: consecutive GitHub alerts (> [!NOTE], > [!WARNING], etc.) require blank lines between them
MD028: false

# MD033/no-inline-html - Inline HTML (allow some elements)
MD033:
  allowed_elements:
    - "br"
    - "sub"
    - "sup"
    - "div"
    - "details"
    - "summary"
    - "strong"

# MD051/link-fragments - Link fragments (disabled: emoji anchors cause issues)
MD051: false

# MD034/no-bare-urls - Bare URL used
MD034: false

# MD036/no-emphasis-as-heading - Emphasis used instead of a heading
MD036: false

# MD041/first-line-heading - First line in a file should be a top-level heading
MD041: true

# MD046/code-block-style - Code block style
MD046:
  style: "fenced"

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"

# MD049/emphasis-style - Emphasis style
MD049:
  style: "asterisk"

# MD050/strong-style - Strong style
MD050:
  style: "asterisk"

# MD040/fenced-code-language - Fenced code blocks should have a language
# Disabled: some blocks are plain text output
MD040: false

# MD060/table-column-style - Table column style
# Disabled: too strict for our formatting
MD060: false

# MD029/ol-prefix - Ordered list item prefix
# Disabled: lists separated by code blocks are seen as separate lists
MD029: false
