//! Audit-only property-based test suite — 2026-05-09.
//!
//! These properties were generated by Task 14 of the
//! `docs/superpowers/plans/2026-05-09-full-security-audit.md` campaign.
//! They encode invariants discovered during Phase B (Task 5
//! audit-context-building) and the open questions (OQ-003, OQ-004,
//! OQ-011) recorded in `docs/audit-2026-05-09-findings.md`.
//!
//! These tests may move into the regular test files (`src/security/validator.rs`
//! `mod tests`, etc.) once the implementation has stabilised.

// Property 1 — validator blacklist normalization MUST defeat IFS / ANSI-C
// whitespace encodings. For any blacklisted command pattern, all known
// shell-equivalent encodings of the whitespace MUST also be rejected.
//
// Encodings tested: literal space, `${IFS}`, `$IFS`, `$'\t'`, `$'\n'`,
// `$' '`, line continuation `\<NL>`. These are the encodings the
// `normalize_for_blacklist_match` function at `src/security/validator.rs:55-63`
// claims to handle.

use mcp_ssh_bridge::config::SecurityConfig;
use mcp_ssh_bridge::security::CommandValidator;
use proptest::prelude::*;

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 200,
        ..ProptestConfig::default()
    })]

    #[test]
    fn validator_blacklist_normalization_resists_whitespace_encodings(
        encoding_idx in 0usize..7,
    ) {
        let cfg = SecurityConfig::default();
        let validator = CommandValidator::new(&cfg);

        // The default blacklist includes `(?i)rm\s+-rf\s+/`. Test every
        // known encoding of whitespace between the tokens.
        let encodings = [" ", "${IFS}", "$IFS", "$'\\t'", "$'\\n'", "$' '", "\\\n"];
        let ws = encodings[encoding_idx];
        let cmd = format!("rm{ws}-rf{ws}/");

        let result = validator.validate(&cmd);
        prop_assert!(
            result.is_err(),
            "Encoding {:?} (`{}`) MUST be rejected by blacklist normalization, got Ok for cmd: {:?}",
            ws,
            ws,
            cmd
        );
    }
}

// Property 2 — validator blacklist normalization gap: hex / octal /
// default-value-expansion encodings of whitespace are NOT covered by
// `normalize_for_blacklist_match`. Documents the OQ-003 / OQ-004 gap as
// a passive no-panic test.
//
// If this test starts asserting `is_err()` and passing, the gap has been
// closed.
proptest! {
    #![proptest_config(ProptestConfig {
        cases: 50,
        ..ProptestConfig::default()
    })]

    #[test]
    fn validator_does_not_normalize_hex_or_default_value_expansion(
        encoding_idx in 0usize..2,
    ) {
        let cfg = SecurityConfig::default();
        let validator = CommandValidator::new(&cfg);

        // OQ-003 / OQ-004: these encodings are NOT in the normalize list.
        let encodings = [r"$'\x09'", r"${IFS:- }"];
        let ws = encodings[encoding_idx];
        let cmd = format!("rm{ws}-rf{ws}/");

        let result = validator.validate(&cmd);
        // We expect the command to NOT be caught by the blacklist regex
        // (it would only match if the encoding were normalized to literal
        // whitespace). The blacklist still scans the unnormalized text, so
        // patterns without `\s+` tokens may still fire. The default whitelist
        // is empty, so the standard mode also rejects on whitelist miss.
        // The property here is just: the validator returns SOME result
        // (no panic). Tracking the actual normalize coverage is the
        // OQ-003/004 audit follow-up.
        let _ = result;
        prop_assert!(true, "no panic on encoded whitespace input");
    }
}

// Property 3 + 4 (runbook validator + apply_template invariants) — DEFERRED.
// `validate_runbook`, `apply_template`, `Runbook` are not currently part of
// the public crate API (`mcp_ssh_bridge::domain::runbook` is `pub(crate)`).
// To activate these properties, either expose those symbols behind a
// `pub use` in `src/lib.rs` for testing, or move the proptest cases into
// `src/domain/runbook.rs` as inline `#[cfg(test)] mod tests`.
// Tracked as part of OQ-011 follow-up.
